name: Publish Documentation

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
      
          echo ${{ secrets.SECRET_KEY }}
